plugin: community.digitalocean.digitalocean
attributes:
    - id
    - name
    - memory
    - vcpus
    - disk
    - size
    - image
    - networks
    - volume_ids
    - tags
    - region
groups:
    webservers: "'frontend' in (do_tags)"
    backend_servers: "'application' in (do_tags)"
compose:
    ansible_host: do_networks.v4 | selectattr('type','eq','public')
      | map(attribute='ip_address') | first
